<?php
/*
 * DocaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DocaLib\Tests;

use DocaLib\Exceptions\ApiException;
use DocaLib\Exceptions;
use DocaLib\ApiHelper;
use DocaLib\Models;
use PHPUnit\Framework\TestCase;

class MiscControllerTest extends TestCase
{
    /**
     * @var \DocaLib\Controllers\MiscController Controller instance
     */
    protected static $controller;

    /**
     * @var HttpCallBackCatcher Callback
     */
    protected static $httpResponse;

    /**
     * Setup test class
     */
    public static function setUpBeforeClass(): void
    {
        self::$httpResponse = new HttpCallBackCatcher();
        self::$controller = ClientFactory::create(self::$httpResponse)->getMiscController();
    }


    /**
     * Todo Add description for test testInitiatePayment
     */
    public function testInitiatePayment()
    {
        // Parameters for the API call
        $accept = 'application/json';
        $body = TestHelper::getJsonMapper()->mapClass(json_decode(
            '{
  "amount": "100",
  "currency": "GBP",
  "email": "yourmail@example.com",
  "firs' .
            't_name": "John",
  "last_name": "Doe",
  "callback_url": "https://webhook.site/9d0b00b' .
            'a-9a69-44fa-a43d-a82c33c36fdc",
  "return_url": "https://webhook.site",
  "tx_ref": "4' .
            '5234ggv65rfdrhdbggsed",
  "customization": {
    "title": "Test Payment",
    "descri' .
            'ption": "Payment Description"
  },
  "meta": {
    "uuid": "uuid",
    "response": "' .
            'Response"
  }
}'),
            'DocaLib\Models\\InitiatePaymentRequest'
        );

        // Set callback and perform API call
        try {
            self::$controller->initiatePayment($accept, $body);
        } catch (ApiException $e) {
        }

        // Test response code
        $this->assertEquals(
            200,
            self::$httpResponse->getResponse()->getStatusCode(),
            "Status is not 200"
        );
    }
}
