<?php

declare(strict_types=1);

/*
 * DocaLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace DocaLib\Models;

use stdClass;

class Meta implements \JsonSerializable
{
    /**
     * @var string
     */
    private $uuid;

    /**
     * @var string
     */
    private $response;

    /**
     * @param string $uuid
     * @param string $response
     */
    public function __construct(string $uuid, string $response)
    {
        $this->uuid = $uuid;
        $this->response = $response;
    }

    /**
     * Returns Uuid.
     */
    public function getUuid(): string
    {
        return $this->uuid;
    }

    /**
     * Sets Uuid.
     *
     * @required
     * @maps uuid
     */
    public function setUuid(string $uuid): void
    {
        $this->uuid = $uuid;
    }

    /**
     * Returns Response.
     */
    public function getResponse(): string
    {
        return $this->response;
    }

    /**
     * Sets Response.
     *
     * @required
     * @maps response
     */
    public function setResponse(string $response): void
    {
        $this->response = $response;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['uuid']     = $this->uuid;
        $json['response'] = $this->response;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
